// Code generated by protoc-gen-go. DO NOT EDIT.
// source: preferences.proto

/*
Package preferences is a generated protocol buffer package.

It is generated from these files:
	preferences.proto

It has these top-level messages:
	PreferenceDataRequest
	PreferenceDataResponse
	PreferenceData
*/
package preferences

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PreferenceDataRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PreferenceDataRequest) Reset()                    { *m = PreferenceDataRequest{} }
func (m *PreferenceDataRequest) String() string            { return proto.CompactTextString(m) }
func (*PreferenceDataRequest) ProtoMessage()               {}
func (*PreferenceDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PreferenceDataRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PreferenceDataResponse struct {
	Preferences []*PreferenceData `protobuf:"bytes,1,rep,name=preferences" json:"preferences,omitempty"`
}

func (m *PreferenceDataResponse) Reset()                    { *m = PreferenceDataResponse{} }
func (m *PreferenceDataResponse) String() string            { return proto.CompactTextString(m) }
func (*PreferenceDataResponse) ProtoMessage()               {}
func (*PreferenceDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PreferenceDataResponse) GetPreferences() []*PreferenceData {
	if m != nil {
		return m.Preferences
	}
	return nil
}

type PreferenceData struct {
	Title       string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *PreferenceData) Reset()                    { *m = PreferenceData{} }
func (m *PreferenceData) String() string            { return proto.CompactTextString(m) }
func (*PreferenceData) ProtoMessage()               {}
func (*PreferenceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PreferenceData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PreferenceData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*PreferenceDataRequest)(nil), "PreferenceDataRequest")
	proto.RegisterType((*PreferenceDataResponse)(nil), "PreferenceDataResponse")
	proto.RegisterType((*PreferenceData)(nil), "PreferenceData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GetPreferenceData service

type GetPreferenceDataClient interface {
	GetPreference(ctx context.Context, in *PreferenceDataRequest, opts ...grpc.CallOption) (*PreferenceDataResponse, error)
}

type getPreferenceDataClient struct {
	cc *grpc.ClientConn
}

func NewGetPreferenceDataClient(cc *grpc.ClientConn) GetPreferenceDataClient {
	return &getPreferenceDataClient{cc}
}

func (c *getPreferenceDataClient) GetPreference(ctx context.Context, in *PreferenceDataRequest, opts ...grpc.CallOption) (*PreferenceDataResponse, error) {
	out := new(PreferenceDataResponse)
	err := grpc.Invoke(ctx, "/GetPreferenceData/GetPreference", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetPreferenceData service

type GetPreferenceDataServer interface {
	GetPreference(context.Context, *PreferenceDataRequest) (*PreferenceDataResponse, error)
}

func RegisterGetPreferenceDataServer(s *grpc.Server, srv GetPreferenceDataServer) {
	s.RegisterService(&_GetPreferenceData_serviceDesc, srv)
}

func _GetPreferenceData_GetPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferenceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetPreferenceDataServer).GetPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GetPreferenceData/GetPreference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetPreferenceDataServer).GetPreference(ctx, req.(*PreferenceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetPreferenceData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GetPreferenceData",
	HandlerType: (*GetPreferenceDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreference",
			Handler:    _GetPreferenceData_GetPreference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "preferences.proto",
}

func init() { proto.RegisterFile("preferences.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0x4a, 0x4d,
	0x4b, 0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe7,
	0x12, 0x0d, 0x80, 0x0b, 0xba, 0x24, 0x96, 0x24, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x28,
	0x79, 0x73, 0x89, 0xa1, 0x2b, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x32, 0xe4, 0xe2, 0x46,
	0x32, 0x57, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x5f, 0x0f, 0x4d, 0x35, 0xb2, 0x1a, 0x25,
	0x0f, 0x2e, 0x3e, 0x54, 0x69, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92, 0x9c, 0x54, 0xb0, 0x8d,
	0x9c, 0x41, 0x10, 0x8e, 0x90, 0x02, 0x17, 0x77, 0x4a, 0x6a, 0x71, 0x72, 0x51, 0x66, 0x41, 0x49,
	0x66, 0x7e, 0x9e, 0x04, 0x13, 0x58, 0x0e, 0x59, 0xc8, 0x28, 0x9c, 0x4b, 0xd0, 0x3d, 0xb5, 0x04,
	0xcd, 0x30, 0x27, 0x2e, 0x5e, 0x14, 0x41, 0x21, 0x31, 0x3d, 0xac, 0x9e, 0x94, 0x12, 0xd7, 0xc3,
	0xee, 0x27, 0x25, 0x86, 0x24, 0x36, 0x70, 0xf8, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc6,
	0x17, 0xcc, 0x79, 0x34, 0x01, 0x00, 0x00,
}
